### ISSUE TITLE
stage generation

### ISSUE THREAD

**Issue by ParadoxGopher** [LordMaarten/cgj-19#15]
we need to get a stage going with
- tiles to walk on
- tiles that kill
- tiles that block
more in #9

**Comment by sala7ef** [comment]
water Tiles .. probably fits in the tiles that kills category ... 
again have no clue about the best res. you want so i exported 512px and 128px ... more variations can be done 

![water_tile_01_128](https://user-images.githubusercontent.com/7190925/63900102-bc081300-c9ff-11e9-91c5-f24c94f7fee0.png)
![water_tile_01_512](https://user-images.githubusercontent.com/7190925/63900103-bc081300-c9ff-11e9-8233-e159cd12784b.png)
![water_tile_02_128](https://user-images.githubusercontent.com/7190925/63900104-bc081300-c9ff-11e9-823f-16193985006a.png)
![water_tile_02_512](https://user-images.githubusercontent.com/7190925/63900105-bc081300-c9ff-11e9-8e39-a09b3cdb6b50.png)

**Comment by ParadoxGopher** [comment]
we should talk about the stage i guess...
## will it be a field?
### tiles
- grass
- stone
- fire
- water
### props
- tree
- grass
- ??
## will it be a house?
### tiles
- wooden floor
- stone floor
- fire
- lava?
### props
- tables
- doors
- ??

what do you guys think ? @sala7ef @LordMaarten

**Comment by sala7ef** [comment]
i vote for field .. it’s easier to find props for it that gives damage as well .. rocks .. mountains .. hills .. holes .. spiky bush .. etc.

**Comment by ParadoxGopher** [comment]
i could not get the cropping working in unity and for the randomized rotation we need a scripted brush :-D so i would say lets do that maybe last

**Comment by sala7ef** [comment]
okay .. i fixed the cropping issue , now all tiles are edge to edge .. 

created a bunch of new world assets .. i imagine it can be something like this :

- **tiles to walk on:**
      floor x2 variations with 2 different colors.
      water x2 if you gain the Jesus spell (?!) O.O .. other that that u drown n die.

- **tiles that kill :** 
     Fire.
     volcano.
     grass ( they qualify as spikes .. may be only one of them kills you the one with darker shade of green)

- **tiles that block:**
     trees 
     stones
     the other grass

**Comment by ParadoxGopher** [comment]
cool will try to implement them in the game and then close this issue

**Comment by ParadoxGopher** [comment]
closing this now because we should focus on other stuff
